# Generated by Django 6.0.1 on 2026-01-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя игрока')),
                ('position', models.PositiveSmallIntegerField(default=1, help_text='Число от 1 до 20', verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.PositiveSmallIntegerField(help_text='Фиксированный ID от 1 до 20', primary_key=True, serialize=False, verbose_name='ID задания')),
                ('description', models.TextField(blank=True, verbose_name='Описание задания')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['id'],
            },
        ),
    ]
