# Generated by Django 6.0.1 on 2026-01-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст правил')),
            ],
            options={
                'verbose_name': 'Правила',
                'verbose_name_plural': 'Правила',
            },
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.PositiveSmallIntegerField(default=1, help_text='Число от 0 до 21', verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.PositiveSmallIntegerField(help_text='Фиксированный ID от 1 до 21', primary_key=True, serialize=False, verbose_name='ID задания'),
        ),
    ]
