# Generated by Django 6.0.1 on 2026-01-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rules_alter_player_position_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.PositiveSmallIntegerField(help_text='Фиксированный ID от 1 до 20', primary_key=True, serialize=False, verbose_name='ID задания'),
        ),
    ]
